language: php

php:
  - '5.4'
  - '5.5'
  - '7.0'
  - hhvm

before_script:
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.3' ]; then ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/; fi"
